# wg0 — configuración de peers (SIN PrivateKey del servidor)
# La config completa con PrivateKey está SOLO en /etc/wireguard/wg0.conf
#
# Interface: 10.10.0.1/24  |  ListenPort: 51820

# ── Asus / Windows (Richard) ────────────────────────────────
[Peer]
PublicKey  = KN/kFA0NFshGRIz6Dd4gOcDh7i6jb+8BrV9cw7/n7S0=
AllowedIPs = 10.10.0.2/32

# ── M1 (Linux) ──────────────────────────────────────────────
[Peer]
PublicKey  = 2dBBWqGnQChSGSUeO05AfishTIX2RtJlSgGc+ZbswB0=
AllowedIPs = 10.10.0.4/32

# ── agustina — keypair 2026-05-29 ───────────────────────────
[Peer]
PublicKey = Z2g8Y4vyRCunSTu4qSXza/Ye1qzOR07l78zbkATa+XY=
AllowedIPs = 10.10.0.5/32

# ── agostina — keypair 2026-05-29 ───────────────────────────
[Peer]
PublicKey = P8My8TofzNH6vpw9jIUKxacNyvE/xtAVDpqRiby/TSM=
AllowedIPs = 10.10.0.6/32

# ── mauro — keypair 2026-05-29 ──────────────────────────────
[Peer]
PublicKey = iavEtmxpvt97xgJR8hPbnoS98OocnIMvLJ1Zh8zk2yg=
AllowedIPs = 10.10.0.7/32

# ── martina — keypair 2026-05-21 ────────────────────────────
[Peer]
PublicKey = aZ+NJnGcmLipVKgAX7byBxMUBXARMp9ZahrhCf22WWg=
AllowedIPs = 10.10.0.8/32
